model: 
  name: DPTNet
filterbank:
  n_filters: 64
  kernel_size: 16
  stride: 8
# Network config
masknet:
  in_chan: 64
  out_chan: 64
  ff_hid: 256
  ff_activation: "relu"
  norm_type: "gLN"
  chunk_size: 100
  hop_size: 50
  n_repeats: 2
  mask_act: 'sigmoid'
  bidirectional: true
  dropout: 0
# Training config
training:
  epochs: 100
  batch_size: 2
  num_workers: 24
  half_lr: yes
  early_stop: yes
  gradient_clipping: 5
# Optim config
optim:
  optimizer: adam
  lr: 0.001
  weight_decay: !!float 1e-5
scheduler:
  steps_per_epoch: 10000
  d_model: 64
# Data config
data:
  train_dir: podcastmix/metadata/train
  valid_dir: podcastmix/metadata/val
  sample_rate: 44100
  n_src: 2
  segment: 2
