model: 
  name: UNet
# Training config
training:
  epochs: 100
  batch_size: 2
  num_workers: 2
  half_lr: yes
  early_stop: yes
# Optim config
stft:
  fft_size: 4096
  window_size: 4096
  hop_size: 256
convolution:
  stride: 2
  kernel_size: 5
optim:
  optimizer: adam
  lr: 0.001
  weight_decay: !!float 1e-5
# Data config
data:
  train_dir: podcastmix/metadata/train
  valid_dir: podcastmix/metadata/val
  sample_rate: 44160
  n_src: 2
  segment: 2
