model: 
  name: OpenUnmix
# Training config
training:
  epochs: 100
  batch_size: 2
  num_workers: 2
  half_lr: yes
  early_stop: yes
# Optim config
stft:
  nb_bins: 4096
  window_size: 4096
  hop_size: 256
optim:
  optimizer: adam
  lr: 0.001
  weight_decay: !!float 1e-5
# Data config
data:
  train_dir: podcastmix/metadata/train
  valid_dir: podcastmix/metadata/val
  sample_rate: 44100
  n_src: 2
  segment: 2
