model: 
  name: DPRNNTasNet
model_init: 
  norm_type: "gLN"
  mask_act: "sigmoid"
  bidirectional: True
  rnn_type: "LSTM"
  num_layers: 1
  dropout: 0
  in_chan: 
  fb_name: "free"
  kernel_size: 16
  n_filters: 64
  stride: 8
  encoder_activation: 
  who_is_pinv: 
  padding: 0
  output_padding: 0
# Training config
training:
  epochs: 200
  batch_size: 6
  num_workers: 4
  half_lr: yes
  early_stop: yes
# Optim config
optim:
  optimizer: adam
  lr: 0.001
  weight_decay: 0.
# Data config
data:
  task: linear_mono
  train_dir: podcastmix/metadata/train
  valid_dir: podcastmix/metadata/val
  sample_rate: 44100
  n_src: 2
  segment: 2
