model: 
  name: ConvTasNet
# filterbank config
filterbank:
  n_filters: 1024
  kernel_size: 16
  stride: 4
# Network config
masknet:
  n_blocks: 6
  n_repeats: 3
  mask_act: relu
  bn_chan: 512
  skip_chan: 512
  hid_chan: 512
# Training config
training:
  epochs: 100
  batch_size: 1
  num_workers: 12
  half_lr: yes
  early_stop: yes
  multi_speakers: yes
# Optim config
optim:
  optimizer: adam
  lr: 0.0001
  weight_decay: 0.
# Data config
data:
  original_sample_rate: 44100
  train_dir: podcastmix/podcastmix-synth/metadata/train
  valid_dir: podcastmix/podcastmix-synth/metadata/val
  sample_rate: 44100
  n_src: 2
  segment: 2
