model: 
  name: ConvTasNet
# filterbank config
filterbank:
  n_filters: 512
  kernel_size: 16
  stride: 8
# Network config
masknet:
  n_blocks: 8
  n_repeats: 3
  mask_act: relu
  bn_chan: 256
  skip_chan: 256
  hid_chan: 256
# Training config
training:
  epochs: 30
  batch_size: 2
  num_workers: 24
  half_lr: yes
  early_stop: yes
  multi_speakers: no
# Optim config
optim:
  optimizer: adam
  lr: 0.0005
  weight_decay: 0.
# Data config
data:
  train_dir: podcastmix/metadata/train
  valid_dir: podcastmix/metadata/val
  sample_rate: 8192
  n_src: 2
  segment: 2
