model: 
  name: ConvTasNet
# filterbank config
filterbank:
  n_filters: 512
  kernel_size: 16
  stride: 4
# Network config
masknet:
  n_blocks: 3
  n_repeats: 3
  mask_act: relu
  bn_chan: 128
  skip_chan: 128
  hid_chan: 128
# Training config
training:
  epochs: 100
  batch_size: 1
  num_workers: 12
  half_lr: yes
  early_stop: yes
  multi_speakers: yes
  normalize: no
# Optim config
optim:
  optimizer: adam
  lr: 0.0001
  weight_decay: 0.
# Data config
data:
  original_sample_rate: 44100
  domain: time
  train_dir: podcastmix/metadata/train
  valid_dir: podcastmix/metadata/val
  sample_rate: 44100
  n_src: 2
  segment: 2
  fft_size: no
  hop_size: no
  window_size: 1024
