convolution:
  kernel_size: 5
  stride: 2
data:
  n_src: 2
  sample_rate: 44160
  segment: 2
  train_dir: podcastmix/metadata/train
  valid_dir: podcastmix/metadata/val
main_args:
  config_model: UNet_model/UNet_config.yml
  exp_dir: exp/tmp
  help: null
  resume_from: UNet_model/exp/tmp/checkpoints/epoch=37-step=294423.ckpt
model:
  name: UNet
optim:
  lr: 0.001
  optimizer: adam
  weight_decay: 1.0e-05
positional arguments: {}
stft:
  fft_size: 4096
  hop_size: 256
  window_size: 4096
training:
  batch_size: 2
  early_stop: true
  epochs: 100
  half_lr: true
  num_workers: 2
