model: 
  name: UNet
# Training config
training:
  epochs: 100
  batch_size: 1
  num_workers: 12
  half_lr: yes
  early_stop: no
  multi_speakers: yes
convolution:
  stride: 2
  kernel_size: 5
optim:
  optimizer: adam
  lr: 0.0001
  weight_decay: 0.
# Data config
data:
  original_sample_rate: 44100
  fft_size: 2048
  window_size: 2048
  hop_size: 441
  train_dir: podcastmix/metadata/train
  valid_dir: podcastmix/metadata/val
  sample_rate: 44100
  n_src: 2
  segment: 2
