model: 
  name: UNet
# Training config
training:
  epochs: 100
  batch_size: 1
  num_workers: 2
  half_lr: yes
  early_stop: yes
# Optim config
stft:
  fft_size: 1024
  window_size: 1024
  hop_size: 32
convolution:
  stride_c: 2
  kernel_size_c: 5
  batch_normalization_c: true
  activation_kernel_c: relu
  activation_leakiness_c: 0.2
deconvolution:
  stride_d: 2
  kernel_size_d: 5
  batch_normalization_d: true
  activation_kernel_d: relu
  activation_leakiness_d: 1
  n_layer_dropout_d: 3
  dropout_d: 0.5
  last_layer_activation_d: sigmoid
optim:
  optimizer: adam
  lr: 0.001
  weight_decay: !!float 1e-5
# Data config
data:
  train_dir: podcastmix/metadata/train
  valid_dir: podcastmix/metadata/val
  sample_rate: 44100
  n_src: 2
  segment: 2
