model: 
  name: UNet
# Training config
training:
  epochs: 500
  batch_size: 8
  num_workers: 24
  half_lr: yes
  early_stop: yes
  multi_speakers: no
# Optim config
stft:
  fft_size: 1024
  window_size: 1024
  hop_size: 441
convolution:
  stride: 2
  kernel_size: 5
optim:
  optimizer: adam
  lr: 0.0005
  weight_decay: !!float 1e-5
# Data config
data:
  train_dir: podcastmix/metadata/train
  valid_dir: podcastmix/metadata/val
  sample_rate: 44100
  n_src: 2
  segment: 2
