data:
  n_src: 1
  sample_rate: 8000
  segment: 3
  task: linear_mono
  train_dir: augmented_dataset/metadata/train
  valid_dir: augmented_dataset/metadata/val
demask_net:
  activation: relu
  dropout: 0
  hidden_dims:
  - 1024
  input_type: mag
  mask_act: relu
  norm_type: gLN
  output_type: mag
filterbank:
  fb_type: stft
  fix_length_mode: pad
  kernel_size: 512
  n_filters: 512
  stride: 256
main_args:
  config_model: DeMask_model/DeMask_config.yml
  exp_dir: exp/tmp
  help: null
model:
  name: DeMask
optim:
  lr: 0.001
  optimizer: adam
  weight_decay: 0.0
positional arguments: {}
training:
  batch_size: 6
  early_stop: true
  epochs: 5
  half_lr: true
  num_workers: 4
