model: 
  name: LSTMTasNet
model_init:
  bn_chan: 128
  num_blocks: 16
  upsampling_depth: 4
  mask_act: "softmax"
  fb_name: "free"
# Training config
training:
  epochs: 5
  batch_size: 6
  num_workers: 4
  half_lr: yes
  early_stop: yes
# Optim config
optim:
  optimizer: adam
  lr: 0.001
  weight_decay: 0.
# Data config
data:
  task: linear_mono
  train_dir: augmented_dataset/metadata/train
  valid_dir: augmented_dataset/metadata/val
  sample_rate: 8000
  n_src: 2
  segment: 3
