model: 
  name: DeMask
filterbank:
  fb_type: stft
  n_filters: 512
  kernel_size: 512
  stride: 256
  fix_length_mode: pad
demask_net:
  input_type: mag
  output_type: mag
  hidden_dims: [1024]
  dropout: 0
  activation: relu
  mask_act: relu
  norm_type: gLN
# Training config
training:
  epochs: 5
  batch_size: 6
  num_workers: 4
  half_lr: yes
  early_stop: yes
# Optim config
optim:
  optimizer: adam
  lr: 0.001
  weight_decay: 0.
# Data config
data:
  task: linear_mono
  train_dir: augmented_dataset/metadata/train
  valid_dir: augmented_dataset/metadata/val
  sample_rate: 8000
  n_src: 2
  segment: 3
